# 開発環境用のDockerfile

FROM node:20-alpine
WORKDIR /app

# package.jsonを先にコピーして依存関係キャッシュ最適化
COPY package*.json ./
RUN npm install

COPY . .

ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL

EXPOSE 3000
CMD ["npm", "run", "dev"]