services:
  db:
    image: postgres:15
    container_name: ramen_blog_db 
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: ramen_blog_backend
    volumes:
      - ./backend:/app
    ports:
      - "${SERVER_PORT:-8080}:8080"
    env_file:
      - .env
    depends_on:
      - db

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: ramen_blog_swagger
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /app/openapi.yaml
    volumes:
      - ./docs/openapi.yaml:/app/openapi.yaml:ro 
    restart: unless-stopped
volumes:
  db_data:
